### ISSUE TITLE
Problème dans l'affichage

### ISSUE THREAD

**Issue by Henrylefou** [augustin7698/EcoleDirecte-Average#1]
Bonjour, j'ai installé l'extension mais je vois que au niveau de l'affichage de la moyenne, quelque chose ne fonctionne pas. auriez vous la réponse ?
Merci

**Comment by augustin7698** [comment]
O.K pour régler ton problème est ce que tu pourrais me faire une capture d'écran ?

**Comment by augustin7698** [comment]
> Bonjour, j'ai installé l'extension mais je vois que au niveau de l'affichage de la moyenne, quelque chose ne fonctionne pas. auriez vous la réponse ?
> 

Merci, est ce que tu pourrais expliquer ce qui ne fonctionne pas plus précisément ou me faire une capture d'écran de la zone ?

**Comment by Henrylefou** [comment]
![image](https://user-images.githubusercontent.com/113796358/204030359-cfeb0855-c72c-4191-9dec-0f59fc5f8833.png)


voilà une partie

**Comment by Henrylefou** [comment]
![image](https://user-images.githubusercontent.com/113796358/204030597-021e4209-fd68-48dc-9a7f-ee735f20af01.png)


et voici la seconde, ces carrés blanc sont au nombre de 11.

**Comment by augustin7698** [comment]
je pense avoir réglé le problème (au moins pour l'affichage de la moyenne), tu peut désinstaller et réinstaller l’extension, et tu pourra me dire si ça marche (pense bien a supprimer complètement les fichiers de la version précédentes pour ne pas te tromper de fichiers pour la réinstallation).

**Comment by Henrylefou** [comment]
![image](https://user-images.githubusercontent.com/113796358/204087037-cccf3579-ad30-4f2e-a0ab-53cabef10f37.png)

Génial merci ! mais je ne vois plus les notes...dois-je désactiver l'extension le  temps de voir les notes et la remette pour voir la moyenne générale ?
Sinon, merci beaucoup

**Comment by augustin7698** [comment]
J'ai réglé le problème (du coup tu peut réitérer la réinstallation), puis dit moi si ça a bien marché. :)

**Comment by Henrylefou** [comment]
c'est parfait merci beaucoup, un travail de ouf ! Aucun problème ! Bravo

**Comment by augustin7698** [comment]
Merci beaucoup pour tes retours, si tu veux tu peut t’abonner à mon compte GitHub et mettre une étoile à mon projet.
A+.
